SkillsFundingAgency/dfc-devops

ArmTemplates/README.md, ArmTemplates/sqlserver-elasticpool.json, ArmTemplates/sqlserver-elasticpool.md, Tests/A003.ArmTemplates.sqlserver-elasticpool.Tests.ps1, Tests/sample.ps1
Added a SQL Server linked template with option to create elastic pool as well
=> DASD-4123 SQL server template

ArmTemplates/README.md, ArmTemplates/azure-search.json, ArmTemplates/azure-search.md, ArmTemplates/cosmos-db.json, ArmTemplates/cosmos-db.md, ArmTemplates/keyvault-secrets.json, ArmTemplates/keyvault-secrets.md, ArmTemplates/keyvault.md, ArmTemplates/sqlserver-elasticpool.md, Tests/A004.ArmTemplates.cosmos-db.Tests.ps1, Tests/A005.ArmTemplates.azure-search.Tests.ps1
* Added Azure Search and Cosmos DB templates with full test.
* Added a companion template for keyvaults. Not easy to automate the test but has been manually tested.
=> DASD-4403 Azure Search, Cosmos DB and Keyvault secrets ARM templates

PSScripts/ReadMe.md
=> DASD-4522 Updated readme

ArmTemplates/README.md, ArmTemplates/storage-account.json, ArmTemplates/storage-account.md, Tests/A006.ArmTemplates.StorageAccount.Tests.ps1
Storage account clone from DAS building blocks
=> NCSD-63 Storage account

ArmTemplates/README.md, ArmTemplates/application-insights.json, ArmTemplates/application-insights.md, Tests/A011.ArmTemplates.AppplicationInsights.ps1
Copy of app insights template from das-platform-building-blocks with tag done correctly. Added usual doc and test files
=> NCSD-125 App Insights template

ArmTemplates/README.md, ArmTemplates/app-service.json, ArmTemplates/app-service.md, ArmTemplates/certificate.json, ArmTemplates/certificate.md, Tests/A008.ArmTemplates.KeyVaultCertificates.Tests.ps1, Tests/A009.ArmTemplates.AppService.Tests.ps1, Tests/A012.ArmTemplates.Certificate.Tests.ps1
App service template can now create function apps and certificate template copied from DAS building blocks
=> NCSD-125 Certificate and function apps

PSScripts/Rename-ConfigFiles.ps1, Tests/U005.PSScripts.Rename-ConfigFiles.Tests.ps1
=> NCSD-204 Rename config files

PSScripts/Get-GitTags.ps1, Tests/U004.PSScripts.Get-GitTags.Tests.ps1
Added Get-GitTags to tag builds in VSTS with the tags in git
=> NCSD-195 git tags

PSScripts/Set-EsfaResourceGroupTags.ps1, Tests/U004.PSScripts.Set-EsfaResourceGroupTags.Tests.ps1
Fixed resource group tagging when no tags present in existing resource group
=> NCSD-230 rg tagging

ArmTemplates/README.md, ArmTemplates/azure-search.json, ArmTemplates/certificate.md, ArmTemplates/redis.json, ArmTemplates/redis.md, Tests/A013.ArmTemplates.redis.Tests.ps1
Added template for creating Redis cache
=> NCSD-263 Redis template added

ArmTemplates/redis.json
Added alternative Redis connection string (for Sitefinity)
=> NCSD-263 redis connection string

ArmTemplates/README.md, ArmTemplates/cognitive-services.json, ArmTemplates/cognitive-services.md, Tests/A015.ArmTemplates.CognitiveServices.Tests.ps1
Added Cognitive Services account template
=> NCSD-264 Cognitive Services

PSScripts/Set-CorsOnStorageAccount.ps1, Tests/U006.PSScripts.Set-CorsOnStorageAccount.Tests.ps1
Added Set-CorsOnStorageAccount.ps1 for setting CORS headers on a storage account
=> NCSD-301 Set-CorsOnStorageAccount.ps1

PSScripts/New-DatabaseFromBlobFile.ps1, Tests/U010.PSScripts.New-DatabaseFromBlobFile.Tests.ps1
Added New-DatabaseFromBlobFile.ps1 to restore a db from blob storage
=> NCSD-325 New-DatabaseFromBlobFile.ps1

PSScripts/Invoke-SqlScript.ps1, PSScripts/Set-SqlLoginPassword.ps1, Tests/U011.PSScripts.Set-SqlLoginPassword.Tests.ps1, Tests/U012.PSScripts.Invoke-SqlScript.Tests.ps1
Added Set-SqlLoginPassword.sql
=> NCSD-327 Set-SqlLoginPassword

PSScripts/Switch-SqlDatabases.ps1, Tests/U013.PSScripts.Switch-SqlDatabases.Tests.ps1
=> NCSD-330 DB rename

PSScripts/Get-AppServiceAppSetting.ps1, Tests/U014.PSScripts.Get-AppServiceAppSetting.Tests.ps1
Added Get-AppServiceAppSetting.ps1
=> NCSD-354: get app settings

PSScripts/New-CosmosDbAccountCollections.ps1
Added try catch around Get-CosmosDb calls to catch any 404 error bubbling up
=> NCSD-388 404 fix

PSScripts/Switch-SqlDatabases.ps1, Tests/U013.PSScripts.Switch-SqlDatabases.Tests.ps1
Changed Get/Find-AzureRmResource to Get-AzureRmSqlDatabase to fix dbdetection in Switch-SqlDatabases.sql
=> NCSD-391: Fixed Switch-SqlDatabases.sql

PSScripts/Set-SqlLoginPassword.ps1, Tests/U011.PSScripts.Set-SqlLoginPassword.Tests.ps1
Added check to ensure db is online before continuing in Set-SqlLoginPassword.ps1
=> NCSD-392: Set-SqlLoginPassword fix

PSScripts/Clear-Cdn.ps1, Tests/U015.PSScripts.Clear-Cdn.Tests.ps1
Added Clear-Cdn.ps1 to purge (all by default) content from a CDN endpoint
=> NCSD-420: Added Clear-Cdn.ps1

ArmTemplates/README.md, ArmTemplates/managed-instance-environment.json, ArmTemplates/managed-instance-environment.md, ArmTemplates/sql-managed-instance.json, ArmTemplates/sql-managed-instance.md, ArmTemplates/sql-server.md, PSScripts/New-CosmosDbAccountCollections.ps1
* Added SQL managed instance template
* Fix route table on managed instance environment template
* Fix New-CosmosDbAccountCollections.ps1
=> NCSD-429: SQL managed instance deployment to VNet

PSScripts/Set-StorageContainer.ps1, Tests/U016.PSScripts.Set-StorageContainer.Tests.ps1
Added Set-StorageContainer.ps1 to create storage account container
=> NCSD-567: Storage container

ArmTemplates/sql-server.json
Added line of code to Active Directory dependsOn 'AuditPolicyName' to allow Elastic Pool to build first.
=> Active Directory dependsOn added

ArmTemplates/app-service.md, PSModules/AzureApiFunctions.md, PSModules/AzureApiFunctions.psm1, PSModules/README.md, PSScripts/Set-SearchDataSources.ps1, README.md, Tests/U017.PSModules.AzureSearchFunctions.Tests.ps1, Tests/U018.PSScripts.Set-SearchDataSources.Tests.ps1
Added Set-SearchDataSources.ps1 a datasource creation script
=> NCSD-707: Set-SearchDataSources.ps1

ArmTemplates/README.md, ArmTemplates/ServiceBus/service-bus.json, ArmTemplates/ServiceBus/service-bus.md
* Add a namespace template
* Add documentation
* Update documentation index
* Add missing services to documentation index
* 🐔
=> NCSD-814 Add service bus namespace

ArmTemplates/README.md, ArmTemplates/network.json, ArmTemplates/network.md
Changed managed-instance-environment.json to network.json and added non-routed subnets
=> NCSD-841: Network (vnet)

ArmTemplates/README.md, ArmTemplates/public-ip.json, ArmTemplates/public-ip.md
Added public-ip.json ARM template
=> NCSD-870: public-ip.json

ArmTemplates/app-service.json, ArmTemplates/app-service.md
Can now set ARR Affinity (sticky sessions) in app-service.json
=> NCSD-998: Sticky sessions

ArmTemplates/app-service.json
NCSD-1082:  Disable php on the web apps
=> NCSD-1082: Removes php support from app services

PSScripts/New-CosmosDbAccountCollections.ps1, Tests/U009.PSScripts.New-CosmosDbAccountCollections.Tests.ps1
New-CosmosDbAccountCollections.ps1 now updates RU (OfferThroughput) if changed
=> NCSD-1111: RU updates

PSScripts/New-CosmosDbAccountCollections.ps1, Tests/U009.PSScripts.New-CosmosDbAccountCollections.Tests.ps1
Finds the offer associated to the collection and updates this iff the OfferThrougput has changed
=> NCSD-1111: OfferThrougput update

ArmTemplates/README.md, ArmTemplates/ServiceBus/servicebus-topic-subscription.json, ArmTemplates/ServiceBus/servicebus-topic-subscription.md, ArmTemplates/ServiceBus/servicebus-topic.json, ArmTemplates/ServiceBus/servicebus-topic.md, Tests/A020.ArmTemplates.ServiceBusTopic.Tests.ps1, Tests/A021.ArmTemplates.ServiceBusTopicSubscription.Tests.ps1
Service Bus topic and topic subscription templates added with simple pester test
=> NCSD-1862: Service Bus topic + subscription templates

ArmTemplates/README.md, ArmTemplates/ServiceBus/servicebus-topic-authrule.json, ArmTemplates/ServiceBus/servicebus-topic-authrule.md, Tests/A022.ArmTemplates.ServiceBusQueueAuthRule.Tests.ps1, Tests/A023.ArmTemplates.ServiceBusTopicAuthRule.Tests.ps1
Added a topic authorization rule (shared access policy) the same as queue has
=> NCSD-1970: Topic auth rule

PSModules/CompositeRegistrationFunctions.psm1
Added additional logging for POST and PATCH commands so that the body is outputted. This will allow debugged of issues around registration.json
=> NCSD-2302: Composite registration verbose logging

AzureDevOpsTemplates/Build/StepTemplates/dfc-grunt-build.yml, AzureDevOpsTemplates/Build/StepTemplates/dfc-gulp-build.yml
Added optional prefix for the display name for when this is being called mulitple times (eg dfc-digital-assets)
=> NCSD-2448: Node build template name prefixes

AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml, AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build.yml
Updates dfc-dotnetcore-build.yml to produce pipeline artifacts rather than build artifacts
=> NCSD-2553: Updates dfc-arm-build.yml to always produce artifacts

PSCoreScripts/Copy-SitefinityDatabase.ps1, Tests/powershellcore/U031.PSCoreScripts.Copy-SitefinityDatabase.Tests.ps1
Update of the copy database script, which copies the current Sitefinity database to the new release, to use Az module instead
=> NCSD-2626: copy Sitefinity db

PSCoreScripts/New-ApimProduct.ps1, Tests/powershellcore/U034.PSScripts.New-ApimProduct.Tests.ps1
New-ApimProduct.ps1 checks if APIM product exists first and creates one if not
=> NCSD-3137: Non-destructive creation of APIM product

ArmTemplates/apim-service.json, ArmTemplates/apim-service.md
Allows the capacity (units) to be set for the APIM
=> NCSD-3394: APIM scaling

PSCoreScripts/New-EventGridSubscription.ps1, PSCoreScripts/Set-ApimPolicy.ps1
- added set-apimpolicy.ps1
- added New-EventGridSubscription.ps1
=> Set apimpolicy

PSScripts/Export-import-CosmosDbCollections.ps1
This to try and export cosmos collections straight from Prod DB into a target environment
=> export cosmos collections straight from Prod to target

PSScripts/Export-import-CosmosDbCollections.ps1, PSScripts/New-DatabaseFromBlobFile.ps1, Tests/arm/A015.ArmTemplates.CognitiveServices.Tests.ps1, Tests/powershell5_1/U010.PSScripts.New-DatabaseFromBlobFile.Tests.ps1
AzureRm commands will be deprecated from February 2024. This PR migrates AzureRm to Az modules.
=> Modify SQL import to update from AzureRm commands.

PSScripts/Add-AzureAdApiPermissionsToApp.ps1, PSScripts/Add-KeyVaultCertificate.ps1, PSScripts/Clear-Cdn.ps1, PSScripts/Get-AppServiceAppSetting.ps1, PSScripts/Import-ApimSwaggerApiDefinition.ps1, PSScripts/New-ApplicationRegistration.ps1, PSScripts/New-CosmosDbAccountCollections.ps1, PSScripts/New-KeyVault.ps1, PSScripts/Set-CorsOnStorageAccount.ps1, PSScripts/Set-EsfaResourceGroupTags.ps1, PSScripts/Set-SearchDataSources.ps1, PSScripts/Set-SearchIndexers.ps1, PSScripts/Set-SearchIndexes.ps1, PSScripts/Set-SqlLoginPassword.ps1, PSScripts/Set-StorageContainer.ps1, PSScripts/Start-SSISIntegrationRuntime.ps1, PSScripts/Switch-SqlDatabases.ps1, PSScripts/Test-ArmTemplate.ps1, Resources/AzureDevOps/StageTemplates/RunTests.yml, Tests/arm/A001.PSScripts.Test-ARMTemplate.Tests.ps1
All files migrated,  not 100% confident in the Clear-Cdn.ps1 and New-ApplicationRegistration.ps1 upgrades
=> Az Module Migration

PSScripts/Set-EsfaResourceGroupTags.ps1
Import Az.Resources for tagging script.
=> Update Set-EsfaResourceGroupTags.ps1 script to import
